### ISSUE TITLE
How i can save dialog progres 

### ISSUE THREAD

**Issue by Iilinkasa** [aibexhq/botscripten#467]
Hi! 
How i can save dialog progres ?

**Comment by thecodedrift** [comment]
Because botscripten only parses the twine files and directives, it doesn't offer any state itself. Using the [npm module](https://github.com/jakobo/botscripten#-node-module-documentation), you can extract the set of passages and preserve the last node the user visited. Unfortunately, internal state management is outside of what we were building with botscripten.
